version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: meeting_rooms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres:5432/meeting_rooms
      NEXTAUTH_SECRET: armboy122
      NEXTAUTH_URL: https://meeting-rooms.akin.love
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: